# Generated by Django 5.2.4 on 2025-07-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
