# Generated by Django 5.2.4 on 2025-07-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Id',
            new_name='eid',
        ),
    ]
